### ISSUE TITLE
Appearance of Graph Visualisation and Infobar

### ISSUE THREAD

**Issue by StanRonzhin** [PDOK/LinkDaLe#86]
![image](https://user-images.githubusercontent.com/14327516/30898519-0e04fc1c-a35c-11e7-9216-c495587776f9.png)

**Comment by StanRonzhin** [comment]
Text in a circle (in the center):
Class
Person

Text in a rectangle (in the centre):
{name of column(e.g it should be Name instead of Person)}

In the inforbar:
for classes:
Class:{class name}  - (e.g Class:Person) class name is clickable like Person_uri now
{ontology}
{(expandable) List of example values ()}

For relations:
Property:{Property name} - ()

**Comment by GerwinBosch** [comment]
The smaller text on the top is a static value, so for the URI nodes it works however not for the literals, for now I will be renaming them to ```raw value```

**Comment by GerwinBosch** [comment]
@StanRonzhin What was the request?

**Comment by GerwinBosch** [comment]
Fixed with #110
